#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: GetData()
#
# Description:
#   Get data from json file.
#
# Usage:
#   GetData key value
#
# Examples:
#   GetData 1 "message"
#

function GetData() {

  local _FUNCTION_ID="GetData"
  local _STATE="0"

  _msg=""

  local _key="$1"
  local _value="$2"

  export _msg=$(jq -r ".[${_key}].${_value}" ${_fd})

  return "$_STATE"

}

function __main__() {

  local _FUNCTION_ID="__main__"
  local _STATE="0"

  local _param="$1"

  readonly _fd="templates/_data.json"
  readonly _template="templates/_template.html"

  local _http_code=""

  local _count=$(jq -r ".[].code" ${_fd} | wc -l)
  local _end=$((_count - 1))

  for i in $(seq 0 $_end) ; do

    GetData "${i}" "code"

    _http_code="$_msg"

    cp "$_template" "site/${_http_code}.html"

    GetData "${i}" "title"
    _http_title="$_msg"

    sed -i "s/HTTP_CODE/${_http_code} ${_http_title}/g" "site/${_http_code}.html"

    GetData "${i}" "desc"
    _http_desc="$_msg"

    sed -i "s/HTTP_DESCRIPTION/${_http_desc}/g" "site/${_http_code}.html"

    sed "s/^[ \t]*//" -i "site/${_http_code}.html"

  done

}

# We pass arguments to the __main__ function.
# It is required if you want to run on arguments type $1, $2, ...
__main__ "${__script_params[@]}"
