#!/usr/bin/env bash

# The array that store call parameters.
# shellcheck disable=SC2034
__init_params=()
__script_params=("$@")

# ``````````````````````````````````````````````````````````````````````````````
# Function name: GetData()
#
# Description:
#   Get data from json file.
#
# Usage:
#   GetData key value
#
# Examples:
#   GetData 1 "message"
#

function GetData() {

  local _FUNCTION_ID="GetData"
  local _STATE="0"

  _msg=""

  local _key="$1"
  local _value="$2"

  export _msg=$(jq -r ".[${_key}].${_value}" ${_jsonf})

  return "$_STATE"

}

function __main__() {

  local _FUNCTION_ID="__main__"
  local _STATE="0"

  local _param="${__script_params[0]}"

  local _templates="templates"
  local _static="static"
  local _http_code=""

  if [[ "$_param" -eq "400" ]] ; then

    readonly _jsonf="src/4xx.json"
    readonly _fdir="${_static}/4xx"
    readonly _fa_img="fas fa-info-circle orange"

  elif [[ "$_param" -eq "500" ]] ; then

    readonly _jsonf="src/5xx.json"
    readonly _fdir="${_static}/5xx"
    readonly _fa_img="fas fa-exclamation-triangle red"

  elif [[ "$_param" -eq "other" ]] ; then

    readonly _fdir="${_static}/other"

    cp "${_templates}/_maintenance.html" "${_fdir}/maintenance.html"
    cp "${_templates}/_invalid-domain.html" "${_fdir}/invalid-domain.html"
    cp "${_templates}/_rate-limit.html" "${_fdir}/rate-limit.html"

  else

    printf "%s\n" "INFO: unknown param"
    exit 1

  fi

  mkdir -p ${_fdir}
  cp src/main.css ${_static}

  local _count=$(jq -r ".[].code" ${_jsonf} | wc -l)
  local _end=$((_count - 1))

  for i in $(seq 0 $_end) ; do

    GetData "${i}" "code"
    _http_code="$_msg"

    cp "${_templates}/_template.html" "${_fdir}/${_http_code}.html"

    GetData "${i}" "title"
    _http_title="$_msg"

    sed -i "s/HTTP_CODE/${_http_code} ${_http_title}/g" "${_fdir}/${_http_code}.html"

    GetData "${i}" "desc"
    _http_desc="$_msg"

    sed -i "s/HTTP_DESCRIPTION/${_http_desc}/g" "${_fdir}/${_http_code}.html"
    sed -i "s/FA_IMG/${_fa_img}/g" "${_fdir}/${_http_code}.html"

    sed "s/^[ \t]*//" -i "${_fdir}/${_http_code}.html"

  done

}

# We pass arguments to the __main__ function.
# It is required if you want to run on arguments type $1, $2, ...
__main__ "${__script_params[@]}"
